# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_HOST: "185.204.3.140"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global lerna
    - run: lerna bootstrap
    - run: npm run build:client
    - uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: $PRIVATE_KEY
        SOURCE: "packages/client/dist/"
        REMOTE_HOST: $REMOTE_HOST
        REMOTE_USER: "ci"
        TARGET: "/var/www/secreate/html/"

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: $PRIVATE_KEY
        name: id_rsa # optional
        known_hosts: $REMOTE_HOST

    - run: ssh ci@${{ env.REMOTE_HOST }} "cd /home/secreate/;git pull;lerna bootstrap;killall node;nohup npm run start:server &"
